config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home_show/:id', to: 'home#show', as: 'home_show'
  resources :teams
  resources :users
  resource :sessions, only: [:new, :create, :destroy]


  root({ to: 'home#index' })
  patch 'update_user_followed_teams', to: "teams#update_user_followed_teams"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_teams

  helper_method :find_team_logo, :find_team_score, :find_match_date, :get_game_winner

  def index
    @all_future_matches = future_matches
    @all_past_matches = past_matches
    @filtered_future_matches = []
    @filtered_past_matches = []

    if current_user
      current_user.team_followings.each do |team|
        @filtered_future_matches << FilterMatchesByTeamService.new(@all_future_matches, team.team.slug).filter_matches.flatten
        @filtered_past_matches << FilterMatchesByTeamService.new(@all_past_matches, team.team.slug).filter_matches.flatten
      end

      @all_filtered_future_matches = @filtered_future_matches.flatten
      @all_filtered_past_matches = @filtered_past_matches.flatten
    end
  end

  def show
    @match = PandascoreApiService.new().get_match_by_id(params[:id]).first
    @games = @match['games']
    @team1 = Team.where(api_team_id: @match['opponents'].first['opponent']['id']).first
    @team2 = Team.where(api_team_id: @match['opponents'].last['opponent']['id']).first
    
    # render json: @games
  end

  private

  def future_matches    
    all_matches = []
    @future_nalcs_matches = PandascoreApiService.new({league_id: 4198}).get_future_matches
    @future_lec_matches = PandascoreApiService.new({league_id: 4197}).get_future_matches
    all_matches << @future_nalcs_matches
    all_matches << @future_lec_matches

    all_matches.flatten
  end

  def past_matches
    all_matches = []
    @past_nalcs_matches = PandascoreApiService.new({league_id: 4198}).get_past_matches
    @past_lec_matches = PandascoreApiService.new({league_id: 4197}).get_past_matches
    all_matches << @past_nalcs_matches
    all_matches << @past_lec_matches

    all_matches.flatten
  end

  def user_teams
    [Team.first.slug] # current_user.teams
  end

  def find_team_logo(team)
    team['opponent']['slug']
  end

  def find_team_score(results, team)
    @team_id = team['opponent']['id']
    if results.first['team_id'] == @team_id
      return results.first['score']
    else results.second['team_id'] == @team_id
      return results.second['score']
    end
  end

  def find_match_date(match)
    @date = match['begin_at']
    Date.parse(@date).strftime('%B %d, %Y')
  end

  def get_game_winner(winner_id)
    @winner = PandascoreApiService.new({team_id: winner_id}).get_team_by_id
    @winner.first
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_display_past_matches.html.erb
<div class="container home__matches-accordion-section">
  <div id="past-accordion">
    <div class="card">
      <div class="card-header" id="allPastMatchesHeader">
        <h5 class="mb-0">
          <button class="btn home__matches-collapse-button" data-toggle="collapse" data-target="#allPastMatches" aria-expanded="true" aria-controls="allPastMatches">
            All Past Matches
          </button>
        </h5>
      </div>

      <div id="allPastMatches" class="collapse show" aria-labelledby="allPastMatchesHeader" data-parent="#past-accordion">
        <div class="card-body">
          <% if all_matches.count == 0 %>
            <p class="home__none-to-display-text">None to display...</p>
          <% else %>
            <% all_matches.each do |match| %>
              <%= link_to home_show_path(match['id']), class: 'home__match_show_link' do %>
                <%= render 'shared/match_cards', match: match, location: 'past' %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <% team_matches.each_with_index do |matches, index| %>
      <div class="card">
        <div class="card-header" id="heading-past-<%=index%>">
          <h5 class="mb-0">
            <%= button_tag "Past Matches for #{current_user.team_followings[index].team['name']}", class: "btn collapsed home__matches-collapse-button", data: { toggle: "collapse", target: "#collapse-past-#{index}"}, aria: {expanded: false, controls: "collapse-past-#{index}"} %>
          </h5>
        </div>
        <div id="collapse-past-<%=index%>" class="collapse" aria-labelledby="heading-past-<%=index%>" data-parent="#past-accordion">
          <div class="card-body">
            <% if matches.empty? %>
              <p class="home__none-to-display-text">None to display...</p>
            <% else %>
              <% matches.each do |match| %>
              <%= link_to home_show_path(match['id']), class: "home__match_show_link" do %>
                <div class="card" style="width: 30rem;">
                  <div class="card-body">
                    <small class='number_of_games'>Best of <%=match['number_of_games']%></small>
                    <span>
                      <h5 class="card-title">
                        <% if File.file?("#{Rails.root}/app/assets/images/team_logo/#{find_team_logo(match['opponents'].first)}.png") %>
                          <%= image_tag "team_logo/#{find_team_logo(match['opponents'].first)}.png", size: "40"%>
                        <% end %>
                        <%= match['opponents'].first['opponent']['name'] %>
                        <%= find_team_score(match['results'], match['opponents'].first) %>
                        -
                        <%= find_team_score(match['results'], match['opponents'].second) %>
                        <%= match['opponents'].second['opponent']['name'] %>
                        <%if File.file?("#{Rails.root}/app/assets/images/team_logo/#{find_team_logo(match['opponents'].second)}.png") %>
                          <%= image_tag "team_logo/#{find_team_logo(match['opponents'].second)}.png", size: "40"%>
                        <% end %>
                      </h5>
                      <p class="match-date"><%= find_match_date(match) %></p>
                    </span>
                    <p class="card-text">Winner: <%= match['winner']['name'] %></p>
                  </div>
                </div>
              <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_display_upcoming_matches.html.erb
<div class="container home__matches-accordion-section">
  <div id="upcoming-accordion">
    <div class="card">
      <div class="card-header" id="allUpcomingMatchesHeader">
        <h5 class="mb-0">
          <button class="btn home__matches-collapse-button" data-toggle="collapse" data-target="#allUpcomingMatches" aria-expanded="true" aria-controls="allUpcomingMatches">
            All Upcoming Matches
          </button>
        </h5>
      </div>

      <div id="allUpcomingMatches" class="collapse show" aria-labelledby="allUpcomingMatchesHeader" data-parent="#upcoming-accordion">
        <div class="card-body">
          <% if all_matches.count == 0 %>
            <p class="home__none-to-display-text">None to display...</p>
          <% else %>
            <% all_matches.each do |match| %>
            <%= link_to home_show_path(match['id']), class: "home__match_show_link" do %>
              <%= render 'shared/match_cards', match: match, location: 'upcoming' %>
            <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <% team_matches.each_with_index do |matches, index| %>
      <div class="card">
        <div class="card-header" id="heading-upcoming-<%=index%>">
          <h5 class="mb-0">
            <%= button_tag "Upcoming Matches for #{current_user.team_followings[index].team['name']}", class: "btn collapsed home__matches-collapse-button", data: { toggle: "collapse", target: "#collapse-upcoming-#{index}"}, aria: {expanded: false, controls: "collapse-upcoming-#{index}"} %>
          </h5>
        </div>
        <div id="collapse-upcoming-<%=index%>" class="collapse" aria-labelledby="heading-upcoming-<%=index%>" data-parent="#upcoming-accordion">
          <div class="card-body">
            <% if matches.empty? %>
              <p class="home__none-to-display-text">None to display...</p>
            <% else %>
              <% matches.each do |match| %>
              <%= link_to home_show_path(match['id']), class: "home__match_show_link" do %>
                <div class="card" style="width: 30rem;">
                  <div class="card-body">
                    <small class='number_of_games'>Best of <%=match['number_of_games']%></small>
                    <span>
                      <h5 class="card-title">
                        <% if File.file?("#{Rails.root}/app/assets/images/team_logo/#{find_team_logo(match['opponents'].first)}.png") %>
                        <%= image_tag "team_logo/#{find_team_logo(match['opponents'].first)}.png", size: "40"%>
                        <% end %>
                        <%= match['opponents'].first['opponent']['name'] %>
                        vs.
                        <%= match['opponents'].second['opponent']['name'] %>
                        <% if File.file?("#{Rails.root}/app/assets/images/team_logo/#{find_team_logo(match['opponents'].second)}.png") %>
                        <%= image_tag "team_logo/#{find_team_logo(match['opponents'].second)}.png", size: "40"%>
                        <% end %>
                      </h5>
                      <p class="match-date"><%= find_match_date(match) %></p>
                    </span>
                  </div>
                </div>
              <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_user_not_logged_in.html.erb
<div class="home__user-not-logged-in-section">
  <%= image_tag("logo_transparent.png", border:0, size: "300") %>


  <h1 class="home__welcome-to-feeder">Welcome to Feeder!</h1>

  <div class="home__not-logged-in-user-option-buttons-section">
    <%= link_to( "Log In", new_sessions_path, class: "btn btn-lg mr-4 home__task-option-buttons") %>
    <%= link_to( "Sign Up", new_user_path, class: "btn btn-lg home__task-option-buttons" )%>
  </div>
</div>

app/views/home/index.html.erb
<%if current_user%>
  <div class="home__matches-tabs-section">
    <ul class="nav nav-tabs directory-nav-center row" id="myTab" role="tablist">
      <span class="col-sm-3"></span>
      <li class="nav-item col-sm-3">
        <a class="nav-link active home__matches-tabs-selection" id="home-tab" data-toggle="tab" href="#upcoming" role="tab" aria-controls="home" aria-selected="true">Upcoming Matches</a>
      </li>
      <li class="nav-item col-sm-3">
        <a class="nav-link home__matches-tabs-selection" id="profile-tab" data-toggle="tab" href="#past" role="tab" aria-controls="profile" aria-selected="false">Past Matches</a>
      </li>
    </ul>
    <div class="tab-content container" id="myTabContent">
      <div id="upcoming" class="tab-pane fade show active">
        <%= render 'home/display_upcoming_matches', all_matches: @all_filtered_future_matches, team_matches: @filtered_future_matches %>
      </div>
      <div id="past" class="tab-pane fade">
        <%= render 'home/display_past_matches', all_matches: @all_filtered_past_matches, team_matches: @filtered_past_matches %>
      </div>
    </div>
  </div>
<%else%>
  <%= render 'home/user_not_logged_in' %>
<%end%>

app/views/home/show.html.erb
<div class="container-fluid">
  <h4 class="home-show__match-history-title"> Match Details</h4>
  <div class="row home-show__match-history-league-and-logo">
    <div class="col-md-6">
      <%= image_tag "#{@match['league']['image_url']}", size: "120" %>
      <span class="home-show__match-history-league-info">
        <%= @match['league']['name'] %>
        <%= @match['serie']['year'] %>
        <%= @match['serie']['season'] %>
        -
        <%= @match['tournament']['name'] %>
      </span>
    </div>
    <div class="col-md-6" style="margin-top: 0.5rem">
      <p class='home-show__match_date'>
        Match
        <% if @match['status'] == 'finished' %>
          Completed
        <% else %>
          Scheduled
        <% end %>
        On:
      </p>
      <h4 class="home-show__match-scheduled-on-date"> <%= find_match_date(@match) %> </h4>
    </div>
  </div>

  <h4 class="home-show__best-of-games-text"> Best of <%= @match['number_of_games']%> </h4>
    <div class="home-show__match-team-one text-center">
      <div class="row home-show__match-history-score">
        <%= link_to team_path(@team1.id), class: "row teams__team-details-link" do %>
          <%= image_tag("team_logo/#{find_team_logo(@match['opponents'].first)}.png", size: "100") %>
          <div class="team home-show__team-name-and-score">
            <div class="col-md">
              <h3 class="team_name"><%=@match['opponents'].first['opponent']['name']%></h3>
              <% if @match['status'] == 'finished' %>
                <p>
                  <% if @match['winner']['name'] == @match['opponents'].first['opponent']['name'] %>
                    VICTORY
                  <%else%>
                    DEFEAT
                  <%end%>
                </p>
              <% end %>
            </div>
          </div>
        <% end %>

        <h5 class="home-show__match-score-result">
          <% if @match['status'] == 'finished'%>
            <%= find_team_score(@match['results'], @match['opponents'].first) %>
            -
            <%= find_team_score(@match['results'], @match['opponents'].second) %>
          <% else %>
            VS
          <% end %>
        </h5>

        <%= link_to team_path(@team2.id), class: "row teams__team-details-link" do %>
          <div class="team home-show__team-name-and-score">
            <div class="col-md">
              <h3 class="team_name"><%=@match['opponents'].last['opponent']['name']%></h3>
              <% if @match['status'] == 'finished' %>
                <p>
                  <% if @match['winner']['name'] == @match['opponents'].last['opponent']['name']%>
                    VICTORY
                  <%else%>
                    DEFEAT
                  <%end%>
                </p>
              <% end %>
            </div>
          </div>
          <%= image_tag("team_logo/#{find_team_logo(@match['opponents'].last)}.png", size: "100") %>
        <% end %>

      </div>
      <span>
    </div>
  
</div>

<% if @match['status'] == 'finished' %>
  <div class="home-show__match-time-completed">
    <% if @games.count > 1 %>
    <div class="row">
      <% @games.each do |game| %>
        <div class="col-sm">
        <h3>Game <%= game['position'] %></h3>
        <h4><%= get_game_winner(game['winner']['id'])['acronym'] %> Win</h4>
        <h5>Duration: <%= game['length'] / 60  %> minutes</h5>
        </div>
      <% end %>
    </div>
    <% elsif @games.count > 0 %>
      <h5>Duration: <%= @games.first['length'] / 60  %> minutes</h5>
    <% end %>
  </div>
<% end %>