config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home_show/:id', to: 'home#show', as: 'home_show'
  resources :teams
  resources :users
  resource :sessions, only: [:new, :create, :destroy]


  root({ to: 'home#index' })
  patch 'update_user_followed_teams', to: "teams#update_user_followed_teams"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('logo_transparent.png'), :rel => 'icon', :type =>  'image/png' %>
    <title>Feeder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag("logo_transparent.png", border:0, size: "50") %> Feeder
          <% end %>
          <div class="navbar-nav ml-auto d-flex">
            <%= link_to("Home", root_path, class: 'nav-link application__navbar-nav-text')%>
            <%= link_to("Teams", teams_path, class: 'nav-link application__navbar-nav-text')%>
          </div>
          <% if user_signed_in? %>
            <div class="navbar-nav ml-auto d-flex">
              <%= link_to("Hello #{current_user.username.titleize}!", user_path(current_user), class: "nav-link") %>
              <%= link_to("Log out", sessions_path, method: :delete, class: "nav-link")%>
            </div>
          <% else %>
            <div class="navbar-nav ml-auto d-flex">
              <%= link_to("Log In", new_sessions_path, class: "nav-link")%>
              <%= link_to("Sign Up", new_user_path, class: "nav-link")%>
            </div>
          <% end %>
        </div>
      </nav>
    </header>



    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>